# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c03a0a4de18926cb48dbc9172c96bf839646e8d7dd28211b6e0d7d71772a5f7827d17bada3e23a096692895c27ed39627ce9649dab04e5f740e16e99549a1cb

test:
  secret_key_base: 84bd4bf14864ed8d576c66c8839167400d18944f11f056ff1bafa5d5605ee8e06808cd84737847dbdce0507b109014149ca1e5eec66d7a79073f61d6ba1afaf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
